name: Gerar Thumbnails

permissions:
  contents: write           # permite gravar no repositório

on:
  push:
    paths:
      - 'imagens7/*.jpg'
      - 'imagens7/*.jpeg'
      - 'imagens7/**/*.jpg'
      - 'imagens7/**/*.jpeg'
  workflow_dispatch:

jobs:
  thumbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0     # necessário para dar push
          lfs: true          # se você usa Git LFS para as fotos

      - name: Instalar ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Criar miniaturas WebP (800 px, 75 %)
        run: |
          shopt -s globstar nullglob
          mkdir -p imagens7/thumbs
          for f in imagens7/*.{jpg,JPG,jpeg,JPEG} imagens7/**/*.{jpg,JPG,jpeg,JPEG}; do
            [ -f "$f" ] || continue
            base=$(basename "$f")
            out="imagens7/thumbs/${base%.*}.webp"
            [ -e "$out" ] && continue
            echo "→ Gerando $out"
            convert "$f" -resize 800x800 -quality 75 "$out"
          done

      - name: Commit & push thumbnails
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain imagens7/thumbs)" ]; then
            git add imagens7/thumbs
            git commit -m "Add/Update thumbnails"
            git push
          else
            echo "Nada a commitar"
          fi
