name: Gerar Thumbnails

permissions:
  contents: write                 # permite gravar no reposit칩rio
  
  concurrency: 
      group: thumbs              # todos os jobs deste workflow entram na mesma fila
      cancel-in-progress: true # s칩 mant칠m o mais recente; aborta o anterior

on:
  push:
    paths:
      - 'imagens7/**/*.jpg'
      - 'imagens7/**/*.jpeg'
  workflow_dispatch:

jobs:
  thumbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # precisamos do hist칩rico completo
          lfs: true               # se suas fotos est칚o em Git LFS

      - name: Instalar ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Criar miniaturas WebP (800 px, 75 %)
        run: |
          shopt -s globstar nullglob
          mkdir -p imagens7/thumbs
          for f in imagens7/*.{jpg,JPG,jpeg,JPEG} imagens7/**/*.{jpg,JPG,jpeg,JPEG}; do
            [ -f "$f" ] || continue
            out="imagens7/thumbs/$(basename "${f%.*}").webp"
            [ -e "$out" ] && continue          # j치 tem? pula
            convert "$f" -resize 800x800 -quality 75 "$out"
          done

      - name: Commit & push thumbnails
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"

          # h치 algo modificado?
          if [ -z "$(git status --porcelain imagens7/thumbs)" ]; then
            echo "Nada a commitar"; exit 0
          fi

          git add imagens7/thumbs
          git commit -m "Add/Update thumbnails"

          游댳git pull --rebase --autostash     # sincroniza com o remoto
          git push
