name: Gerar Thumbnails

permissions:
  contents: write        # ← novo

on:
  push:
    paths:
      - 'imagens7/**/*.jpg'
      - 'imagens7/**/*.jpeg'
  workflow_dispatch:

jobs:
  thumbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       # necessário para poder dar push

      - name: Instalar ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Criar miniaturas WebP (800 px, 75 %)
        run: |
          mkdir -p imagens7/thumbs
          for f in imagens7/**/*.jpg imagens7/**/*.jpeg; do
            [ -e "$f" ] || continue
            base=$(basename "$f")
            convert "$f" -resize 800x800 -quality 75 \
                    "imagens7/thumbs/${base%.*}.webp"
          done

      - name: Commit & push thumbnails
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          CHANGED=$(git status --porcelain | wc -l)
          if [ "$CHANGED" -gt 0 ]; then
            git add imagens7/thumbs
            git commit -m "Add/Update thumbnails"
            git push
          else
            echo "Nada a commitar"
          fi
